//! The Rust policy engine against B2's Python engine: `vectors/b2_policy.json`, generated by
//! `scripts/gen_b2_signer_vectors.py` from B2 agp-next2 b4f2fe5. Same decision (verdict, rule,
//! reason, residuals, approval token and expiry) on the same inputs, plus normalize_dest,
//! sats_from_xbt, the approval messages, ed25519 and sanitize.
use std::sync::Arc;

use serde_json::{json, Value};
use xbt_signer::policy::{normalize_dest, AuditLog, LedgerEntry, Payment, PolicyConfig, PolicyEngine, PolicyStore};

fn vectors() -> Value {
    let p = concat!(env!("CARGO_MANIFEST_DIR"), "/../../vectors/b2_policy.json");
    serde_json::from_str(&std::fs::read_to_string(p).unwrap()).unwrap()
}

#[test]
fn decision_table_matches_b2() {
    let v = vectors();
    let now = v["now"].as_f64().unwrap();
    let cases = v["cases"].as_array().unwrap();
    let mut by_rule = std::collections::BTreeMap::<String, usize>::new();
    let mut bad = vec![];
    for c in cases {
        let d = tempfile::tempdir().unwrap();
        let store = PolicyStore::open(&d.path().join("ledger.json")).unwrap();
        for e in c["ledger"].as_array().unwrap() {
            store.commit(&LedgerEntry { dest: e["dest"].as_str().unwrap().into(), amount_sats: e["amount_sats"].as_i64().unwrap(),
                                        ts: now - e["age_s"].as_f64().unwrap(), txid: "t".into(), memo: String::new() }).unwrap();
        }
        let cfg = PolicyConfig::from_value(&v["configs"][c["config"].as_str().unwrap()]).unwrap();
        let eng = PolicyEngine::new(cfg, store, AuditLog::open(&d.path().join("audit.jsonl")).unwrap(), Some(Arc::new(move || now)));
        let p = &c["payment"];
        let dec = eng.evaluate(&Payment::new(p["dest"].as_str().unwrap(), p["amount_sats"].as_i64().unwrap(), "m"), c["human"].as_bool().unwrap()).unwrap();
        let mut got = dec.as_value();
        got["approval_token"] = got["approval_token"].is_string().into();
        let want = &c["expect"];
        *by_rule.entry(format!("{}/{}", want["verdict"].as_str().unwrap(), want["rule"].as_str().unwrap())).or_default() += 1;
        if &got != want {
            bad.push(format!("{}: want {want}\n      got  {got}", c["id"]));
        }
    }
    println!("policy conformance: {}/{} cases identical", cases.len() - bad.len(), cases.len());
    for (k, n) in &by_rule {
        println!("  {k:28} {n}");
    }
    assert!(bad.is_empty(), "{} mismatches:\n{}", bad.len(), bad.join("\n"));
    assert!(by_rule.len() >= 11, "every rule is exercised: {by_rule:?}");
}

#[test]
fn helpers_match_b2() {
    let v = vectors();
    for pair in v["normalize_dest"].as_array().unwrap() {
        assert_eq!(normalize_dest(pair[0].as_str().unwrap()), pair[1].as_str().unwrap(), "{pair}");
    }
    for pair in v["sats_from_xbt"].as_array().unwrap() {
        let got = xbt_signer::signer::sats_from_xbt(Some(&pair[0]));
        match pair[1].as_i64() {
            Some(want) => assert_eq!(got, Ok(want), "{pair}"),
            None => assert!(got.is_err(), "{pair} should err, got {got:?}"),
        }
    }
    let m = &v["messages"];
    let c = "bcrt1qw508d6qejxtdg4y5r3zarvary0c5xw7kygt080";
    assert_eq!(hex::encode(xbt_signer::approval::canonical_message("tok-_A1", c, 5000, 1790000900)), m["approve"].as_str().unwrap());
    assert_eq!(hex::encode(xbt_signer::approval::recover_message(c, 1790000900)), m["recover"].as_str().unwrap());
    let sweep = xbt_signer::approval::sweep_message(c, "bcrt1qmike", 5200, 1790000900);
    assert_eq!(hex::encode(&sweep), m["sweep"].as_str().unwrap());
    let pk = hex::decode(v["ed25519"]["pub"].as_str().unwrap()).unwrap();
    let sig = hex::decode(v["ed25519"]["sweep_sig"].as_str().unwrap()).unwrap();
    assert!(xbt_signer::approval::verify(&pk, &sweep, &sig), "a signature made by B2's approve CLI verifies");
    assert!(!xbt_signer::approval::verify(&pk, b"other", &sig));
    assert_eq!(xbt_signer::sanitize::sanitize(v["sanitize"]["in"].clone()), v["sanitize"]["out"]);
    let _ = json!(null);
}
