#!/bin/bash
# AGP-030: the xbt-wallet-mcp binary on every AGP-031 target (zig as C compiler and linker, see
# .cargo/config.toml), release and release-small. Records status, size, linkage and a smoke run
# (`--list-tools` must list the ten tools) where this host can execute the binary, in
# dist/MCP_TARGETS.md. Soak: cargo -j2 under CPUQuota=200% / MemoryMax=4G / nice 19. No sudo, no binfmt.
set -uo pipefail
ROOT=$(cd "$(dirname "$0")/../.." && pwd)
cd "$ROOT"
SOAK=(systemd-run --user --scope -q -p CPUQuota=200% -p MemoryMax=4G nice -n 19)
OUT=$ROOT/dist/MCP_TARGETS.md
LOG=$ROOT/dist/logs
mkdir -p "$LOG"
TARGETS=(x86_64-unknown-linux-gnu x86_64-unknown-linux-musl aarch64-unknown-linux-gnu aarch64-unknown-linux-musl
         armv7-unknown-linux-gnueabihf armv7-unknown-linux-musleabihf riscv64gc-unknown-linux-gnu
         x86_64-apple-darwin aarch64-apple-darwin x86_64-pc-windows-gnu)
{
  echo "# xbt-wallet-mcp build matrix"
  echo
  echo "Generated by \`scripts/mcp/build_targets.sh\` at commit \`$(git rev-parse --short HEAD)\`, $(date -u +%Y-%m-%dT%H:%M:%SZ),"
  echo "$(rustc --version), zig $("${XBT_ZIG_PY:-$HOME/.local/share/ziglang-venv/bin/python}" -m ziglang version 2>/dev/null)."
  echo "Smoke: \`xbt-wallet-mcp --list-tools\` lists the ten tools (run only where this x86_64 host can execute the binary)."
  echo
  echo "| target | profile | status | size (bytes) | size | linkage | smoke |"
  echo "|---|---|---|---:|---:|---|---|"
} >"$OUT"
fail=0
for t in "${TARGETS[@]}"; do
  for p in release release-small; do
    exe=xbt-wallet-mcp; [[ $t == *windows* ]] && exe=xbt-wallet-mcp.exe
    bin=$ROOT/target/$t/$p/$exe
    echo "== $t $p"
    if "${SOAK[@]}" cargo build -j2 --profile "$p" --target "$t" -p xbt-wallet-mcp --bin xbt-wallet-mcp >"$LOG/mcp.$t.$p.log" 2>&1 && [ -f "$bin" ]; then
      sz=$(stat -c%s "$bin")
      kind=$(file -b "$bin" | grep -oE "statically linked|static-pie linked|dynamically linked|Mach-O[^,]*|PE32\+[^,]*" | head -1)
      smoke="-"
      if [[ $t == x86_64-unknown-linux-* ]]; then
        n=$("$bin" --list-tools | python3 -c 'import json,sys; print(len(json.load(sys.stdin)["tools"]))' 2>/dev/null)
        [ "$n" = 10 ] && smoke="OK (10 tools)" || { smoke="FAIL ($n)"; fail=1; }
      fi
      echo "| $t | $p | built | $sz | $(awk -v n="$sz" 'BEGIN{printf "%.2f MiB", n/1048576}') | ${kind:-?} | $smoke |" >>"$OUT"
    else
      fail=1
      echo "| $t | $p | FAILED: $(grep -m1 -E '^error' "$LOG/mcp.$t.$p.log" | tr '|' '/' | cut -c1-120) | - | - | - | - |" >>"$OUT"
    fi
  done
done
cat "$OUT"
exit $fail
