#!/bin/bash
# AGP-032: the xbt-work crate on every AGP-031 target (the targets and zig linkers of build_matrix.sh).
# Builds the offline example `work_selftest` (rebuilds the xbt-work vector file on the target and runs
# the 91 conformance checks) in release and release-small, records sizes, runs it where this host can
# (natively: x86_64 glibc and static musl; no binfmt/qemu is installed). Writes dist/WORK_MATRIX.md.
# Soak: cargo -j2 under CPUQuota=200% / MemoryMax=4G / nice 19. CARGO_TARGET_DIR is shared (disk).
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT"
export CARGO_TARGET_DIR=${CARGO_TARGET_DIR:-$HOME/xbt-rnd/xbt-rs-target}
SOAK=(systemd-run --user --scope -q -p CPUQuota=200% -p MemoryMax=4G nice -n 19)
OUT=dist/WORK_MATRIX.md
LOGS=dist/logs; mkdir -p "$LOGS"
TARGETS=(x86_64-unknown-linux-gnu x86_64-unknown-linux-musl aarch64-unknown-linux-gnu aarch64-unknown-linux-musl
         armv7-unknown-linux-gnueabihf armv7-unknown-linux-musleabihf riscv64gc-unknown-linux-gnu
         x86_64-apple-darwin aarch64-apple-darwin x86_64-pc-windows-gnu)
{
  echo "# xbt-work on the AGP-031 targets"
  echo
  echo "Generated by \`scripts/work_matrix.sh\` on **$(date -u +%FT%TZ)** at \`$(git rev-parse --short HEAD)\` ($(rustc --version))."
  echo "Example \`work_selftest\` (crate \`xbt-work\` + \`xbt402\` + \`xbt-primitives\`): rebuilds XBT-053's vector file on the"
  echo "target and runs the 91 conformance checks. Same zig linkers and glibc 2.28 floor as \`dist/MATRIX.md\`."
  echo
  echo "| target | profile | status | bytes | selftest |"
  echo "|---|---|---|---:|---|"
} >"$OUT"
fail=0
for t in "${TARGETS[@]}"; do
  for profile in release release-small; do
    log="$LOGS/work-$t.$profile.log"
    exe=work_selftest; case $t in *windows*) exe=work_selftest.exe ;; esac
    bin="$CARGO_TARGET_DIR/$t/$profile/examples/$exe"
    if "${SOAK[@]}" cargo build -j2 --profile "$profile" --target "$t" -p xbt-work --example work_selftest >"$log" 2>&1 && [ -f "$bin" ]; then
      size=$(stat -c%s "$bin"); run="-"
      if [ "$profile" = release ]; then
        case $t in
          x86_64-unknown-linux-gnu|x86_64-unknown-linux-musl) run=$("$bin" 2>&1 | tr '\n' ' ') || { run="FAIL: $run"; fail=1; } ;;
          *) run="built; not run (no user-mode emulator on this host)" ;;
        esac
      fi
      echo "| \`$t\` | $profile | built | $size | $run |" >>"$OUT"
      echo "  $t $profile: built $size bytes  $run"
    else
      echo "| \`$t\` | $profile | FAILED | - | see $log |" >>"$OUT"; echo "  $t $profile: FAILED ($log)"; fail=1
    fi
  done
done
echo "wrote $OUT"
exit $fail
